language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_script:
  - git config --global user.name "CI"
  - git config --global user.email "ci@travis.com"
script:
  - npm version patch -m "Bumping to %s [skip ci]"
  - git push "https://$GITHUB_TOKEN@github.com/Fley/oeuf.git" HEAD:master
  - npm run build
  - npm test
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master
