export const FETCH_EXERCISES = {
  REQUEST: 'exercises/FETCH_EXERCISES/REQUEST',
  SUCCESS: 'exercises/FETCH_EXERCISES/SUCCESS',
  FAILURE: 'exercises/FETCH_EXERCISES/FAILURE'
};

export const FETCH_EXERCISE = {
  REQUEST: 'exercises/FETCH_EXERCISE/REQUEST',
  SUCCESS: 'exercises/FETCH_EXERCISE/SUCCESS',
  FAILURE: 'exercises/FETCH_EXERCISE/FAILURE'
};

export const ADD_EXERCISE = {
  REQUEST: 'exercises/ADD_EXERCISE/REQUEST',
  SUCCESS: 'exercises/ADD_EXERCISE/SUCCESS',
  FAILURE: 'exercises/ADD_EXERCISE/FAILURE'
};

export const DELETE_EXERCISE = {
  REQUEST: 'exercises/DELETE_EXERCISE/REQUEST',
  SUCCESS: 'exercises/DELETE_EXERCISE/SUCCESS',
  FAILURE: 'exercises/DELETE_EXERCISE/FAILURE'
};

export const ACKNOWLEDGE_EXERCISE = {
  REQUEST: 'exercises/ACKNOWLEDGE_EXERCISE/REQUEST',
  SUCCESS: 'exercises/ACKNOWLEDGE_EXERCISE/SUCCESS',
  FAILURE: 'exercises/ACKNOWLEDGE_EXERCISE/FAILURE'
};

export const CANCEL_EXERCISE = {
  REQUEST: 'exercises/CANCEL_EXERCISE/REQUEST',
  SUCCESS: 'exercises/CANCEL_EXERCISE/SUCCESS',
  FAILURE: 'exercises/CANCEL_EXERCISE/FAILURE'
};

export const ACKNOWLEDGE_EXERCISE_STEP = {
  REQUEST: 'exercises/ACKNOWLEDGE_EXERCISE_STEP/REQUEST',
  SUCCESS: 'exercises/ACKNOWLEDGE_EXERCISE_STEP/SUCCESS',
  FAILURE: 'exercises/ACKNOWLEDGE_EXERCISE_STEP/FAILURE'
};

export const CANCEL_EXERCISE_STEP = {
  REQUEST: 'exercises/CANCEL_EXERCISE_STEP/REQUEST',
  SUCCESS: 'exercises/CANCEL_EXERCISE_STEP/SUCCESS',
  FAILURE: 'exercises/CANCEL_EXERCISE_STEP/FAILURE'
};

export const START_EXERCISE = 'exercises/START';
export const STOP_EXERCISE = 'exercises/STOP';
export const PAUSE_EXERCISE = 'exercises/PAUSE';
